name: Submit a theme
description: Submit a theme to be added to the theme library.
title: "[create-theme]: "
labels: ["new-theme"]
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: The name of the theme. With a maximum of 25 characters.
      placeholder: Theme Name
    validations:
      required: true
  - type: input
    id: description
    attributes:
      label: Description
      description: A brief description of the theme. With a maximum of 100 characters.
      placeholder: Theme Description
    validations:
      required: true
  - type: input
    id: homepage
    attributes:
      label: Homepage
      description: The URL of the theme's homepage or repository.
      placeholder: https://github.com/...
  - type: input
    id: image
    attributes:
      label: Image
      description: "A URL to an image representing the theme. It can be a temporary image, it will be cloned to the theme library. Note: The image must be a PNG file. E.g. an imgur link."
      placeholder: https://...
    validations:
      required: true
  - type: checkboxes
    id: is-color-theme
    attributes:
      label: Type
      description: The type of the theme.
      options:
        - label: JSON Color Theme
    validations:
      required: true
  - type: textarea
    id: styles
    attributes:
      label: Theme Styles
      render: css
      description: The CSS styles for the theme. If the theme is a color theme, the styles should be a JSON object with the color values.
      placeholder: |
        body {
          background-color: white;
          color: black;
        }

        or

        {
          "primaryColor": "#000000",
          ...
        }
    validations:
      required: true
  - type: textarea
    id: readme
    attributes:
      render: markdown
      label: Readme
      description: The README file for the theme.
    validations:
      required: true
  - type: textarea
    id: preferences
    attributes:
      render: json
      label: Preferences
      description: The preferences for the theme in JSON format. Leave empty if there are no preferences. This is not used for color themes.
      placeholder: |
        {
          "uc.my-preference.enable-this": "Enable this feature for the theme",
          "uc.my-preference.show-that": "Show that feature for the theme"
        }